### ISSUE TITLE
npm run devbuild gives error "The system cannot find the path specified."

### ISSUE THREAD

**Issue by hunglam01** [michael-brade/LaTeX.js#140]
Hi Michael,
When I tried to run the step 2. npm run devbuild but got the error "The system cannot find the path specified."
After clone a repository https://github.com/michael-brade/LaTeX.js.git
and follow the instructions on https://latex.js.org/extending.html#architecture

1.  npm install                 -> It created the node_modules directory and subdirectory and files.
2.  npm run devbuild      -> Give the error below.

> latex.js@0.12.4 devbuild
> rimraf 'dist/**/*.map';mkdirp dist/css;mkdirp dist/js;mkdirp dist/fonts;mkdirp dist/documentclasses;mkdirp dist/packages;touch dist/documentclasses/.keep;touch dist/packages/.keep;rsync -a src/css/ dist/css/;rsync -a src/fonts/ dist/fonts/;rsync -a node_modules/katex/dist/fonts/*.woff2 dist/fonts/;rsync -a src/js/ dist/js/;mkdirp bin;lsc -bc --no-header -m embedded -p src/cli.ls > bin/latex.js;chmod a+x bin/latex.js;rollup -c;

The system cannot find the path specified.

Please help. Thanks!

**Comment by michael-brade** [comment]
hm... I think I have fixed this today. Could you please try again?

**Comment by hunglam01** [comment]
I am still getting the same error. I use windows 10 and VS Code. 
Thanks for your help.

**Comment by michael-brade** [comment]
Oh! Now that explains it. I do not support Windows builds at this point, sorry about that. I have no means and no need for it. The built releases should be usable on Windows, though. However, if you find a good way to support Windows, I may accept pull requests :)

PS: I bet it complains because it cannot find rsync on Windows...
